version: master-{build}
image: Visual Studio 2019
configuration: Release
clone_folder: c:\projects\scap-workbench
install:
  - cinst wget
  - cmd: vcpkg install curl libxml2 libxslt bzip2 pcre pthreads zlib getopt-win32
  - cmd: wget https://github.com/OpenSCAP/openscap/releases/download/1.3.3/OpenSCAP-1.3.3-win32.msi -OutFile .\openscap.msi
  - cmd: msiexec /package c:\projects\scap-workbench\openscap.msi /passive

cache: c:\tools\vcpkg\installed\
before_build:
  - cmd: >-
      cd build
      cmake -DENABLE_PYTHON3=FALSE -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
build:
  project: c:\projects\scap-workbench\build\scap-workbench.sln
  verbosity: minimal
after_build:
  - cmd: cpack
artifacts:
  - path: build\*.msi
    name: Windows Installer
  - path: build\*.msi.sha512
    name: SHA512 checksum
